# Create SQL Database
DROP SCHEMA IF EXISTS `flights` ;
CREATE SCHEMA IF NOT EXISTS `flights` DEFAULT CHARACTER SET latin1 ;
USE `flights` ;

# Create Tables
# Data for tables is inserted in another SQL document
CREATE TABLE `airports` (
  `IATA_CODE` VARCHAR(1024),
  `AIRPORT` VARCHAR(1024),
  `CITY` VARCHAR(1024),
  `STATE` VARCHAR(1024),
  `COUNTRY` VARCHAR(1024),
  `LATITUDE` VARCHAR(1024),
  `LONGITUDE` VARCHAR(1024),
  PRIMARY KEY (`IATA_CODE`),
  INDEX `CITY` (`CITY` ASC),
  INDEX `STATE` (`STATE` ASC),
  INDEX `COUNTRY` (`COUNTRY` ASC)
);

CREATE TABLE `airlines` (
  `IATA_CODE` VARCHAR(1024),
  `AIRLINE` VARCHAR(1024),
  PRIMARY KEY (`IATA_CODE`),
  INDEX `AIRLINE` (`AIRLINE` ASC)
);

CREATE TABLE `marflights` (
  `DATE` DATETIME NULL DEFAULT NULL,
  `AIRLINE` VARCHAR(1024),
  `FLIGHT_NUMBER` BIGINT,
  `TAIL_NUMBER` VARCHAR(1024),
  `ORIGIN_AIRPORT` VARCHAR(1024),
  `DESTINATION_AIRPORT` VARCHAR(1024),
  `ELAPSED_TIME` VARCHAR(1024),
  `AIR_TIME` VARCHAR(1024),
  `DISTANCE` BIGINT,
  `ARRIVAL_TIME` VARCHAR(1024),
  `DIVERTED` BIGINT,
  `CANCELLED` BIGINT,
  PRIMARY KEY (`FLIGHT_NUMBER`),
  INDEX `AIRLINE` (`AIRLINE` ASC),
  INDEX `ORIGIN_AIRPORT` (`ORIGIN_AIRPORT` ASC),
  INDEX `DESTINATION_AIRPORT` (`DESTINATION_AIRPORT` ASC),
  FOREIGN KEY (`AIRLINE`) REFERENCES `flights`.`airlines`(`IATA_CODE`),
  FOREIGN KEY (`ORIGIN_AIRPORT`) REFERENCES `flights`.`airports`(`IATA_CODE`),
  FOREIGN KEY (`DESTINATION_AIRPORT`) REFERENCES `flights`.`airports`(`IATA_CODE`),
  FOREIGN KEY (`FLIGHT_NUMBER`) REFERENCES `flights`.`passenger_flights`(`FLIGHT_NUMBER`));
  
#Integrate Date Dimension table
ALTER TABLE `flights`.`marflights`
ADD COLUMN `flight_date_key` int NOT NULL AFTER `DATE`;

UPDATE `flights`.`marflights` AS mf
JOIN `flights`.`dim_date` AS dd
ON DATE(mf.DATE) = dd.`full_date`
SET mf.`flight_date_key` = dd.`date_key`;






